/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "MatchingEngineErrors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MatchingEngineErrors__factory>;
    getContractFactory(
      name: "OrderbookErrors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrderbookErrors__factory>;
    getContractFactory(
      name: "EventfulOrderbook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventfulOrderbook__factory>;
    getContractFactory(
      name: "EventfulOrderbook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventfulOrderbook__factory>;
    getContractFactory(
      name: "MatchingEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MatchingEngine__factory>;
    getContractFactory(
      name: "OrderBook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrderBook__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "MatchingEngineErrors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MatchingEngineErrors>;
    getContractAt(
      name: "OrderbookErrors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OrderbookErrors>;
    getContractAt(
      name: "EventfulOrderbook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EventfulOrderbook>;
    getContractAt(
      name: "EventfulOrderbook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EventfulOrderbook>;
    getContractAt(
      name: "MatchingEngine",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MatchingEngine>;
    getContractAt(
      name: "OrderBook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OrderBook>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
